---
# Source: opentelemetry-collector/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    helm.sh/chart: opentelemetry-collector-0.27.0
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: example
    app.kubernetes.io/version: "0.58.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry-collector
      app.kubernetes.io/instance: example
      component: standalone-collector
  template:
    metadata:
      annotations:
        checksum/config: b2a546144bf9e846203c0c0d021b2169b60761c55b24780f9f4fba080d28db88
      labels:
        app.kubernetes.io/name: opentelemetry-collector
        app.kubernetes.io/instance: example
        component: standalone-collector
    spec:
      serviceAccountName: {{ .Values.name }}
      securityContext: {}
      containers:
        - name: opentelemetry-collector
          command:
            - /otelcol-contrib
            - --config=/conf/relay.yaml
          securityContext: {}
          image: "otel/opentelemetry-collector-contrib:0.58.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: otlp
              containerPort: {{ .Values.grpcPort }}
              protocol: TCP
            - name: otlp-http
              containerPort: {{ .Values.httpPort }}
              protocol: TCP
            - name: fluentforward
              containerPort: {{ .Values.fluentPort }}
              protocol: TCP
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          livenessProbe:
            httpGet:
              path: /
              port: 13133
          readinessProbe:
            httpGet:
              path: /
              port: 13133
          resources:
            limits:
              cpu: 1
              memory: 2Gi
          volumeMounts:
            - mountPath: /conf
              name: opentelemetry-collector-configmap
      volumes:
        - name: opentelemetry-collector-configmap
          configMap:
            name: {{ .Values.name }}
            items:
              - key: relay
                path: relay.yaml
