apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.nginxPort }}
      targetPort: {{ .Values.nginxPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.name }}
